### ISSUE TITLE
Readme error ?

### ISSUE THREAD

**Issue by bhamadicharef** [AgileBitFlipper/triominos#17]
'Playing a triplet gets you the value of the corners added together plus a 10 point bonus. (For example, playing tile '4-4-4' is worth 16 + 10 or 26 points).' 4+4+4 = 12 not 16 ?!

**Comment by AgileBitFlipper** [comment]
Good eye!  Absolutely correct.  The latest develop branch has your fix.  Thank you for pointing that out.

**Comment by bhamadicharef** [comment]
somewhere else there is a "is" which should be an "in" or vice-versa ...
